version: 2.1

executors:
  node-build:
    working_directory: /tmp
    docker:
      - image: circleci/node:13

commands:
  create_concatenated_lockfile:
    description: Create a concatenated yarn.lock file
    steps:
      - run:
          name: Combine all yarn.locks into single lockfile
          command: node scripts/concat-lockfiles.js > combined-yarn.lock

aliases:
  - &save_cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn.lock" }}
  - &restore_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn.lock" }}
        - v1-dependencies-

jobs:
  install:
    executor: node-build
    steps:
      - checkout
      - create_concatenated_lockfile
      - *restore_cache
      - run: yarn install --frozen-lockfile
      - *save_cache

  build:
    executor: node-build
    steps:
      - checkout
      - run: yarn ci:build
      - persist_to_workspace:
          root: /tmp
          paths:
            - node_modules
  test:
    executor: node-build
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run: yarn ci:test

workflows:
  env-development:
    jobs:
      - install
      - test:
          requires:
            - install
