version: 2.1

commands:
  create_concatenated_lockfile:
    description: Create a concatenated yarn.lock file
    steps:
      - run:
          name: Combine all yarn.locks into single lockfile
          command: node scripts/concat-lockfiles.js > combined-yarn.lock

jobs:
  test:
    docker:
      - image: circleci/node:13

    steps:
      - checkout
      - create_concatenated_lockfile
      - restore_cache:
        keys:
          - v1-deps-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - run: yarn ci:test

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn.lock" }}

workflows:
  default:
    jobs:
      - test
