version: 2.1

aliases:
  - &save_cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn.lock" }}
  - &restore_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "combined-yarn.lock" }}
        - v1-dependencies-

executors:
  node-build:
    docker:
      - image: circleci/node:13

commands:
  create_concatenated_lockfile:
    description: Create a concatenated yarn.lock file
    steps:
      - run:
          name: Combine all yarn.locks into single lockfile
          command: node scripts/concat-lockfiles.js > combined-yarn.lock

jobs:
  test:
    executor: node-build
    steps:
      - checkout
      - create_concatenated_lockfile
      - *restore_cache
      - run: yarn install --frozen-lockfile
      - run: yarn ci:test
      - *save_cache

workflows:
  default:
    jobs:
      - test
